stages:
  data_engineering:
    cmd: python code/datasets/data_engineering.py
    deps:
      - code/datasets/data_engineering.py
      - data/raw/
    outs:
      - data/processed/

  model_training:
    cmd: python code/models/train_model.py
    deps:
      - code/models/train_model.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/model.pkl